#ifndef _MIRMOUSE_GLOBALVAR_H_
#define _MIRMOUSE_GLOBALVAR_H_
#if defined DEBUG
#define GRC_VAR_SIZE                    (512)
#define GRC_VAR_INDEX_SIZE              (128)
#define GRC_FRAME_SIZE                  (32)   
#define GRC_MOTER_PID_P_OFFSET              (0)
#define GRC_MOTER_PID_P_SIZE                (4)
#define GRC_MOTER_PID_I_OFFSET              (GRC_MOTER_PID_P_OFFSET + GRC_MOTER_PID_P_SIZE)
#define GRC_MOTER_PID_I_SIZE                (4)
#define GRC_MOTER_PID_D_OFFSET              (GRC_MOTER_PID_I_SIZE + GRC_MOTER_PID_I_SIZE)
#define GRC_MOTER_PID_D_SIZE                (4)
#define GRC_IRSensor_PID_P_OFFSET           (GRC_MOTER_PID_D_OFFSET + GRC_MOTER_PID_D_SIZE)
#define GRC_IRSensor_PID_P_SIZE             (4)
#define GRC_IRSensor_PID_I_OFFSET           (GRC_IRSensor_PID_P_OFFSET + GRC_IRSensor_PID_P_SIZE)
#define GRC_IRSensor_PID_I_SIZE             (4)
#define GRC_IRSensor_PID_D_OFFSET           (GRC_IRSensor_PID_I_OFFSET + GRC_IRSensor_PID_I_SIZE)
#define GRC_IRSensor_PID_D_SIZE             (4) 
#define GRC_IRSensor_RF_A_OFFSET            (GRC_IRSensor_PID_D_OFFSET + GRC_IRSensor_PID_D_SIZE)
#define GRC_IRSensor_RF_A_SIZE              (4)
#define GRC_IRSensor_RF_B_OFFSET            (GRC_IRSensor_RF_A_OFFSET + GRC_IRSensor_RF_A_SIZE)
#define GRC_IRSensor_RF_B_SIZE              (4)
#define GRC_IRSensor_L30_A_OFFSET           (GRC_IRSensor_RF_B_OFFSET + GRC_IRSensor_RF_B_SIZE)
#define GRC_IRSensor_L30_A_SIZE             (4)
#define GRC_IRSensor_L30_B_OFFSET           (GRC_IRSensor_L30_A_OFFSET + GRC_IRSensor_L30_A_SIZE)
#define GRC_IRSensor_L30_B_SIZE             (4)
#define GRC_IRSensor_R30_A_OFFSET           (GRC_IRSensor_L30_B_OFFSET + GRC_IRSensor_L30_B_SIZE)
#define GRC_IRSensor_R30_A_SIZE             (4)
#define GRC_IRSensor_R30_B_OFFSET           (GRC_IRSensor_R30_A_OFFSET + GRC_IRSensor_R30_A_SIZE)
#define GRC_IRSensor_R30_B_SIZE             (4)
#define GRC_IRSensor_LF_A_OFFSET            (GRC_IRSensor_R30_B_OFFSET + GRC_IRSensor_R30_B_SIZE)
#define GRC_IRSensor_LF_A_SIZE              (4)
#define GRC_IRSensor_LF_B_OFFSET            (GRC_IRSensor_LF_A_OFFSET + GRC_IRSensor_LF_A_SIZE)
#define GRC_IRSensor_LF_B_SIZE              (4) 
#define GRC_IRSensor_RF_DIST_OFFSET         (GRC_IRSensor_LF_B_OFFSET+GRC_IRSensor_LF_B_SIZE)
#define GRC_IRSensor_RF_DIST_SIZE           (4)
#define GRC_IRSensor_L30_DIST_OFFSET        (GRC_IRSensor_RF_DIST_OFFSET+GRC_IRSensor_RF_DIST_SIZE)
#define GRC_IRSensor_L30_DIST_SIZE          (4)
#define GRC_IRSensor_R30_DIST_OFFSET        (GRC_IRSensor_L30_DIST_OFFSET+GRC_IRSensor_L30_DIST_SIZE)
#define GRC_IRSensor_R30_DIST_SIZE          (4)
#define GRC_IRSensor_LF_DIST_OFFSET         (GRC_IRSensor_R30_DIST_OFFSET+GRC_IRSensor_R30_DIST_SIZE)
#define GRC_IRSensor_LF_DIST_SIZE           (4)
#define GRC_L_MOTER_STATE_OFFSET            (GRC_IRSensor_LF_DIST_OFFSET+GRC_IRSensor_LF_DIST_SIZE)
#define GRC_L_MOTER_STATE_SIZE              (1)
#define GRC_L_MOTER_DIR_OFFSET              (GRC_L_MOTER_STATE_OFFSET+GRC_L_MOTER_STATE_SIZE)
#define GRC_L_MOTER_DIR_SIZE                (1)
#define GRC_L_MOTER_PULSE_OFFSET            (GRC_L_MOTER_DIR_OFFSET+GRC_L_MOTER_DIR_SIZE)
#define GRC_L_MOTER_PULSE_SIZE              (4)
#define GRC_L_MOTER_PULSECTRL_OFFSET        (GRC_L_MOTER_PULSE_OFFSET+GRC_L_MOTER_PULSE_SIZE)
#define GRC_L_MOTER_PULSECTRL_SIZE          (4)
#define GRC_L_MOTER_INFACT_SPEED_OFFSET     (GRC_L_MOTER_PULSECTRL_OFFSET+GRC_L_MOTER_PULSECTRL_SIZE)
#define GRC_L_MOTER_INFACT_SPEED_SIZE       (4)
#define GRC_L_MOTER_IDLE_SPEED_OFFSET       (GRC_L_MOTER_INFACT_SPEED_OFFSET+GRC_L_MOTER_INFACT_SPEED_SIZE)
#define GRC_L_MOTER_IDLE_SPEED_SIZE         (4)
#define GRC_R_MOTER_STATE_OFFSET            (GRC_L_MOTER_IDLE_SPEED_OFFSET+GRC_L_MOTER_IDLE_SPEED_SIZE)
#define GRC_R_MOTER_STATE_SIZE              (1)
#define GRC_R_MOTER_DIR_OFFSET              (GRC_R_MOTER_STATE_OFFSET+GRC_R_MOTER_STATE_SIZE)
#define GRC_R_MOTER_DIR_SIZE                (1)
#define GRC_R_MOTER_PULSE_OFFSET            (GRC_R_MOTER_DIR_OFFSET+GRC_R_MOTER_DIR_SIZE)
#define GRC_R_MOTER_PULSE_SIZE              (4)
#define GRC_R_MOTER_PULSECTRL_OFFSET        (GRC_R_MOTER_PULSE_OFFSET+GRC_R_MOTER_PULSE_SIZE)
#define GRC_R_MOTER_PULSECTRL_SIZE          (4)
#define GRC_R_MOTER_INFACT_SPEED_OFFSET     (GRC_R_MOTER_PULSECTRL_OFFSET+GRC_R_MOTER_PULSECTRL_SIZE)
#define GRC_R_MOTER_INFACT_SPEED_SIZE       (4)
#define GRC_R_MOTER_IDLE_SPEED_OFFSET       (GRC_R_MOTER_INFACT_SPEED_OFFSET+GRC_R_MOTER_INFACT_SPEED_SIZE)
#define GRC_R_MOTER_IDLE_SPEED_SIZE         (4)
#define GRC_IRSensor_ADCVALUE_RF_OFFSET     (GRC_R_MOTER_IDLE_SPEED_OFFSET+GRC_R_MOTER_IDLE_SPEED_SIZE)
#define GRC_IRSensor_ADCVALUE_RF_SIZE       (2)
#define GRC_IRSensor_ADCVALUE_R30_OFFSET    (GRC_IRSensor_ADCVALUE_RF_OFFSET+GRC_IRSensor_ADCVALUE_RF_SIZE)
#define GRC_IRSensor_ADCVALUE_R30_SIZE      (2)
#define GRC_IRSensor_ADCVALUE_L30_OFFSET    (GRC_IRSensor_ADCVALUE_R30_OFFSET+GRC_IRSensor_ADCVALUE_R30_SIZE)
#define GRC_IRSensor_ADCVALUE_L30_SIZE      (2)
#define GRC_IRSensor_ADCVALUE_LF_OFFSET     (GRC_IRSensor_ADCVALUE_L30_OFFSET+GRC_IRSensor_ADCVALUE_L30_SIZE)
#define GRC_IRSensor_ADCVALUE_LF_SIZE       (2)
#define GRC_GYRO_ADCVALUE_OFFSET            (GRC_IRSensor_ADCVALUE_LF_OFFSET+GRC_IRSensor_ADCVALUE_LF_SIZE)
#define GRC_GYRO_ADCVALUE_SIZE              (2)
#define GRC_VOLTAGE_ADCVALUE_OFFSET         (GRC_GYRO_ADCVALUE_OFFSET+GRC_GYRO_ADCVALUE_SIZE)
#define GRC_VOLTAGE_ADCVALUE_SIZE           (2)
#define GRC_GYRO_BASE_VALUE_OFFSET          (GRC_VOLTAGE_ADCVALUE_OFFSET + GRC_VOLTAGE_ADCVALUE_SIZE)
#define GRC_GYRO_BASE_SIZE                  (2)
#define GRC_GYRO_MUL_PARAM_OFFSET           (GRC_GYRO_BASE_VALUE_OFFSET + GRC_GYRO_BASE_SIZE)
#define GRC_GYRO_MUL_PARAM_SIZE             (4)
#define GRC_GYRO_ANGLE_OFFSET               (GRC_GYRO_MUL_PARAM_OFFSET + GRC_GYRO_MUL_PARAM_SIZE)
#define GRC_GYRO_ANGLE_SIZE                 (4)
#define GRC_MICROMOUSE_POS_X_OFFSET         (GRC_GYRO_ANGLE_OFFSET + GRC_GYRO_ANGLE_SIZE)
#define GRC_MICROMOUSE_POS_X_SIZE           (1)
#define GRC_MICROMOUSE_POS_Y_OFFSET         (GRC_MICROMOUSE_POS_X_OFFSET + GRC_MICROMOUSE_POS_X_SIZE)
#define GRC_MICROMOUSE_POS_Y_SIZE           (1)
#define grc_moter_p                 (*((float*)(grc_var+GRC_MOTER_PID_P_OFFSET)))
#define grc_moter_i                 (*((float*)(grc_var+GRC_MOTER_PID_I_OFFSET)))
#define grc_moter_d                 (*((float*)(grc_var+GRC_MOTER_PID_D_OFFSET)))
#define grc_irsensor_p              (*((float*)(grc_var+GRC_IRSensor_PID_P_OFFSET)))
#define grc_irsensor_i              (*((float*)(grc_var+GRC_IRSensor_PID_I_OFFSET)))
#define grc_irsensor_d              (*((float*)(grc_var+GRC_IRSensor_PID_D_OFFSET)))
#define grc_rf_a                    (*((float*)(grc_var+GRC_IRSensor_RF_A_OFFSET)))
#define grc_rf_b                    (*((float*)(grc_var+GRC_IRSensor_RF_B_OFFSET)))
#define grc_l30_a                   (*((float*)(grc_var+GRC_IRSensor_L30_A_OFFSET)))
#define grc_l30_b                   (*((float*)(grc_var+GRC_IRSensor_L30_B_OFFSET)))
#define grc_r30_a                   (*((float*)(grc_var+GRC_IRSensor_R30_A_OFFSET)))
#define grc_r30_b                   (*((float*)(grc_var+GRC_IRSensor_R30_B_OFFSET)))
#define grc_lf_a                    (*((float*)(grc_var+GRC_IRSensor_LF_A_OFFSET)))
#define grc_lf_b                    (*((float*)(grc_var+GRC_IRSensor_LF_B_OFFSET)))
#define grc_rf_dist                 (*((float*)(grc_var+GRC_IRSensor_RF_DIST_OFFSET)))
#define grc_l30_dist                (*((float*)(grc_var+GRC_IRSensor_L30_DIST_OFFSET)))
#define grc_r30_dist                (*((float*)(grc_var+GRC_IRSensor_R30_DIST_OFFSET)))
#define grc_lf_dist                 (*((float*)(grc_var+GRC_IRSensor_LF_DIST_OFFSET)))
#define grc_irsensor_rf_adc         (*(unsigned short*)(grc_var + GRC_IRSensor_ADCVALUE_RF_OFFSET))
#define grc_irsensor_r30_adc        (*(unsigned short*)(grc_var + GRC_IRSensor_ADCVALUE_R30_OFFSET))
#define grc_irsensor_L30_adc        (*(unsigned short*)(grc_var + GRC_IRSensor_ADCVALUE_L30_OFFSET))
#define grc_irsensor_lf_adc         (*(unsigned short*)(grc_var + GRC_IRSensor_ADCVALUE_LF_OFFSET))
#define grc_gyro_adc                (*(unsigned short*)(grc_var + GRC_GYRO_ADCVALUE_OFFSET))
#define grc_voltage_adc             (*(unsigned short*)(grc_var + GRC_VOLTAGE_ADCVALUE_OFFSET))
#define grc_adc_dma_addr             (grc_var + GRC_IRSensor_ADCVALUE_RF_OFFSET)
#define grc_gyro_base               (*(unsigned short*)(grc_var + GRC_GYRO_BASE_VALUE_OFFSET))
#define grc_gyro_mul_param          (*(float*)(grc_var + GRC_GYRO_MUL_PARAM_OFFSET) )  
#define grc_gyro_angle              (*(float*)(grc_var + GRC_GYRO_ANGLE_OFFSET))
extern char grc_var[GRC_VAR_SIZE];
extern char grc_frame_inf[GRC_FRAME_SIZE];
extern unsigned short  grc_var_index[GRC_VAR_INDEX_SIZE];
#elif defined RELEASE
#endif /* defined DEBUG */
void InitGlobalVar(void);   
#endif /* _MIRMOUSE_GLOBALVAR_H_ */
